# Generated by Django 4.2.4 on 2023-10-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsize',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
    ]
