# Generated by Django 4.2.4 on 2023-10-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0002_alter_roomsize_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='mrtravel_hyphen',
            new_name='mrtravel_hyphin',
        ),
    ]
