# Generated by Django 4.2.4 on 2023-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0003_rename_mrtravel_hyphen_hotelinfo_mrtravel_hyphin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='location',
            field=models.URLField(max_length=500),
        ),
    ]
