# Generated by Django 4.2.4 on 2023-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0004_alter_hotelinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='feature1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature3',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='feature4',
            field=models.CharField(default='', max_length=64),
        ),
    ]
