# Generated by Django 4.2.4 on 2023-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0005_hotelinfo_feature1_hotelinfo_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='feature1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='feature2',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='feature3',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='feature4',
            field=models.CharField(max_length=64),
        ),
    ]
