# Generated by Django 4.2.4 on 2023-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0006_alter_hotelinfo_feature1_alter_hotelinfo_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsize',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
