# Generated by Django 4.2.4 on 2023-10-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0007_alter_roomsize_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='direct_payment_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomsize',
            name='discount_type',
            field=models.CharField(default='first_day', max_length=64),
        ),
    ]
