# Generated by Django 4.2.4 on 2023-11-16 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0008_hotelinfo_direct_payment_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsize',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_rented', to=settings.AUTH_USER_MODEL)),
                ('room_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='mrtravel.roomsize')),
            ],
        ),
    ]
