# Generated by Django 4.2.4 on 2023-11-16 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0009_roomsize_amount_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='date',
        ),
        migrations.AddField(
            model_name='rent',
            name='survey_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
