# Generated by Django 4.2.4 on 2023-11-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0010_remove_rent_date_rent_survey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='room_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='mrtravel.roomsize'),
        ),
    ]
