# Generated by Django 4.2.4 on 2023-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0011_alter_rent_room_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsize',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
