# Generated by Django 4.2.4 on 2023-11-23 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0012_roomsize_available_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
