# Generated by Django 4.2.4 on 2023-11-30 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0013_hotelinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='survey_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
