# Generated by Django 4.2.4 on 2023-12-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0014_rent_survey_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
