# Generated by Django 4.2.4 on 2023-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0016_rent_hotel_alter_rent_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
