# Generated by Django 4.2.4 on 2023-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0017_rent_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
