# Generated by Django 4.2.4 on 2023-12-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtravel', '0018_rent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
